# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Talentora' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  pod 'XCDYouTubeKit', '~> 2.5'

  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-camera', path: '../node_modules/react-native-camera'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
end